plugins {
    id "com.android.application"
}

def holodoriVersion = project.findProperty("holodoriVersionName") ?:
        rootProject.file("../VERSION").text.trim()
def holodoriVersionCode = (project.findProperty("holodoriVersionCode") ?: "7") as int

android {
    namespace "dev.holodori.trackpad"
    compileSdk 35

    defaultConfig {
        applicationId "dev.holodori.trackpad"
        minSdk 23
        targetSdk 35
        versionCode holodoriVersionCode
        versionName holodoriVersion
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation "androidx.profileinstaller:profileinstaller:1.4.1"
}
