plugins {
    id "com.android.application"
}

def holodoriVersion = project.findProperty("holodoriVersionName") ?:
        rootProject.file("../VERSION").text.trim()
def holodoriVersionCode = (project.findProperty("holodoriVersionCode") ?: "27") as int

android {
    namespace "dev.holodori.trackpad"
    compileSdk 35

    defaultConfig {
        applicationId "dev.holodori.trackpad"
        minSdk 23
        targetSdk 35
        versionCode holodoriVersionCode
        versionName holodoriVersion
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation "androidx.profileinstaller:profileinstaller:1.4.1"
    implementation "org.signal.forks:noise-java:0.1.1"
    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.test:runner:1.6.2"
}
